name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose --release --manifest-path=birds/Cargo.toml
    - name: Build (Windows x86)
      run: cargo build --verbose --release --manifest-path=birds/Cargo.toml
    - name: Uploard Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lloids (Windows x86)
        path: birds/target/release/birds.exe

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: sudo apt-get install libasound2-dev
    - name: Build (Linux x86)
      run: cargo build --verbose --release --manifest-path=birds/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --release --manifest-path=birds/Cargo.toml
    - name: Uploard Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lloids (Linux x86)
        path: birds/target/release/birds
